---
title: "stat_project_graph"
author: "Xiaoxiang Zhang"
date: "2018/5/5"
output: html_document
---

```{r}
whitewine <- read.csv(file="./winequality/winequality-white.csv", header=TRUE, sep=";")
#x=cbind(whitewine$fixed.acidity, whitewine$volatile.acidity, whitewine$citric.acid, whitewine$residual.sugar, whitewine$chlorides, whitewine$free.sulfur.dioxide, whitewine$total.sulfur.dioxide, whitewine$density, whitewine$pH, whitewine$sulphates, whitewine$alcohol)
whitewine[,1:11] = scale(whitewine[,1:11])
```


```{r}
max_num= names(which.max(table(whitewine$quality)))
max_num
```

```{r}
summary(whitewine)
```

```{r}
num=rep(0,10)
for (i in 1: dim(red)[1]){
  num[red[i, 12]]= num[red[i, 12]]+1
}
num
```

Histogram
```{r}
red <- read.csv(file="./winequality/winequality-red.csv", header=TRUE, sep=";")
ggplot(data=red, aes(x=quality))  +geom_bar(binwidth=1, color='black', fill='white')
```

```{r}
min(whitewine$quality)
max(whitewine$quality)
mean(whitewine$quality)
```

pairs
```{r}
pairs(whitewine)
```

corelation
```{r}
cor(x=whitewine[,1:11], y=whitewine$quality)
```
citric.acid is unrelated to quality

The relationship between alcohol and quality
```{r}
tapply(whitewine$alcohol, whitewine$quality, mean)
```

```{r}
lm.fit = lm(whitewine$alcohol~whitewine$quality)
summary(lm.fit)
```

white
```{r}
t= seq(1, 11, length.out= 11)
tt= c(0.5841331, 0.5613812, 0.5821929, 0.5841467, 0.631075, 0.6109853, 0.6136292, 0.6195324, 0.6209067, 0.6333171, 0.67016)
ttt= data.frame(t= t, tt=tt)
ggplot(ttt, aes(x=t, y= tt))+geom_line()
```
red
```{r}
t= seq(1, 11, length.out= 11)
tt= c(0.5043261, 0.4913771, 0.5076926, 0.5241781, 0.5249516, 0.5224805, 0.5369605, 0.5471358, 0.5463417, 0.6308551, 0.72045)
ttt= data.frame(t= t, tt=tt)
ggplot(ttt, aes(x=t, y= tt))+geom_line()
```


cv_white
```{r}
t= seq(1, 11, length.out= 11)
tt= c(0.5572518, 0.5568665, 0.553532, 0.5559634, 0.5417427, 0.5495835, 0.5525328, 0.5558522, 0.5909985, 0.6239896, 0.72045)
ttt= data.frame(t= t, tt=tt)
ggplot(ttt, aes(x=t, y= tt))+geom_line()
```

red cv
```{r}
t= seq(0, 2, length.out= 50)
tt= jjj
ttt= data.frame(t= t, tt=tt)
ggplot(ttt, aes(x=t, y= tt))+geom_line()
```




white cv
```{r}
t= seq(0, 2, length.out= 50)
tt= jjj
tt_1= jjj-1
ttt= data.frame(t= t, tt=tt)
ttt1= data.frame(t= t, tt=tt_1)
plot(t, tt)
lines(t, tt_1)
```